apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: development
spec:
  limits:
    - type: Container
      default:                  # default limit
        cpu: "0.5"
        memory: "512Mi"
      defaultRequest:
        cpu: "0.1"
        memory: "256Mi"
      max:
        cpu: "2"
        memory: "2Gi"
      min:
        cpu: "0.1"
        memory: "128Mi"

# create a pod and check the resources which is added to the pod.
