apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resources to be included
resources:
- deployment.yaml
- service.yaml

# Common labels for all resources
labels:
- includeSelectors: true
  pairs:
    project: alpha
